apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: gcr.io/google-samples/node-hello:1.0
      env:
        # Define the environment variable
        - name: DATOS_MYSQL
          valueFrom: # para cargar todas las variables como una sola en bloque
            configMapKeyRef:
              name: datos-mysql-env
              key: datos_mysql.properties
  restartPolicy: Never
